int int1 = 5;
double double1 = 3.14;
print(int1);
print(double1);

string read1;
read(read1);
print(read1);

int addResult = int1 + 10;
int addResult2 = 10 + 15;
double addResult3 = double1 + 4.1;
double addResult4 = 5.2 + 3.4;
print(addResult);
print(addResult2);
print(addResult3);
print(addResult4);

int multResult = int1 * 5;
int multResult2 = 10 * 15;
double multResult3 = double1 * 2.5;
double multResult4 = 1.5 * 1.5;
print(multResult);
print(multResult2);
print(multResult3);
print(multResult4);


